name: camilo jimenez
favicon: null
layout_spectrum: 0.31509
typography_spectrum: 1
title: 'My site '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfffe'
    - '#95749a'
    - '#010008'
    - '#abaad8'
    - '#68e0f9'
  brandStrength: 0.25
  lightness: 0.5477384314872324
  saturation: 0.5625
  rhythmicContrast: 0.1487451116554439
purpose: []
