name: camilo
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#2a343e'
    - '#feba27'
    - '#aea49a'
    - '#7f7a76'
  brandStrength: 0.942412240896374
  lightness: 0.5477384314872324
  saturation: 0.9237772012129426
  rhythmicContrast: 0.1487451116554439
purpose: []
