name: camilo
favicon: null
layout_spectrum: 0.7851652835961431
typography_spectrum: 0.38657849188894033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.942412240896374
  lightness: 0.5477384314872324
  saturation: 0.9237772012129426
  rhythmicContrast: 0.1487451116554439
purpose: []
