name: camilo
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'My site '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff503f'
    - '#272d33'
    - '#aacc4e'
    - '#6e6e6e'
  brandStrength: 0.942412240896374
  lightness: 0.5477384314872324
  saturation: 0.75
  rhythmicContrast: 0.1487451116554439
purpose: []
